"""Deterministic, zero-cost providers for development, tests and dry-runs.

Stages register task handlers (e.g. "v2v_plan", "story_plan") that turn the structured payload into
the same kind of output a real model would return, so every pipeline can run end to end offline.
Mock output is always flagged ``simulated=True`` and never counted as real model work.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw

from .base import ImageProvider, ImageResult, LLMProvider, LLMResult, Usage, estimate_tokens

MockHandler = Callable[[dict[str, Any]], str]
MOCK_HANDLERS: dict[str, MockHandler] = {}


def register_mock(task: str) -> Callable[[MockHandler], MockHandler]:
    def decorator(fn: MockHandler) -> MockHandler:
        MOCK_HANDLERS[task] = fn
        return fn
    return decorator


class MockLLM(LLMProvider):
    name = "mock"
    model = "mock"

    def complete(self, *, system: str, user: str, images: list[Path] | None = None, json_mode: bool = False,
                 task: str | None = None, payload: dict[str, Any] | None = None) -> LLMResult:
        handler = MOCK_HANDLERS.get(task or "")
        if handler is not None:
            text = handler(payload or {})
        elif json_mode:
            text = json.dumps({"mock": True, "task": task}, ensure_ascii=False)
        else:
            text = f"[mock:{task or 'generic'}]\n{user[:2000]}"
        usage = Usage(input_tokens=estimate_tokens(system) + estimate_tokens(user) + 1100 * len(images or []),
                      output_tokens=estimate_tokens(text))
        digest = hashlib.sha1((task or "").encode() + user.encode("utf-8")).hexdigest()[:12]
        return LLMResult(text=text, usage=usage, model=self.model, request_id=f"mock-{digest}", simulated=True)


class MockImage(ImageProvider):
    name = "mock"
    model = "mock"

    def __init__(self, size: tuple[int, int] = (1536, 864)) -> None:
        self.size = size

    def generate(self, *, prompt: str, input_files: list[Path], out_path: Path, image_id: str) -> ImageResult:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        image = Image.new("RGB", self.size, (205, 205, 205))
        draw = ImageDraw.Draw(image)
        lines = [f"MOCK IMAGE  {image_id}", "not generated by a real model",
                 f"inputs: {len(input_files)}", f"prompt sha1: {hashlib.sha1(prompt.encode('utf-8')).hexdigest()[:16]}"]
        for i, line in enumerate(lines):
            draw.text((40, 40 + 36 * i), line, fill=(60, 60, 60))
        draw.rectangle([4, 4, self.size[0] - 5, self.size[1] - 5], outline=(120, 120, 120), width=6)
        image.save(out_path)
        return ImageResult(path=out_path, usage=Usage(images=1), model=self.model,
                           request_id=f"mock-{image_id}", simulated=True)
